language: node_js
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
node_js:
  - 12.16.2
before_install:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install

stages:
  - test
  - name: deploy
    if: (tag =~ ^@turbox3d) OR (tag =~ ^turbox)
  - name: deploy-plugin
    if: tag =~ ^@plugin

jobs:
  include:
    - stage: test
      script:
        - lerna bootstrap
        - lerna run build:ts
        - lerna run test
    - stage: deploy
      script:
        - lerna bootstrap
        - lerna run build:all
        - cp .npmrc.template $HOME/.npmrc
        - lerna publish from-package --yes
    - stage: deploy-plugin
      script:
        - cp .vsce.template $HOME/.vsce
        - cd ./plugins/turbox-snippets
        - npx vsce publish
